language: node_js
node_js:
  - "0.10"
script:
  - echo 'CraftWine Web App'
install:
  - npm install -g firebase-tools
after_success:
  - firebase deploy --email fabio.dieguez@gmail.com --password eAdmin.9