language: node_js
node_js:
  - "5.11"
branches:
  only:
    - master
before_script:
  - npm install -g firebase-tools
  - npm install -g wintersmith    
script:
  - echo 'CraftWine Web App'
  - wintersmith build
after_success:
  - firebase deploy --email=${FIREBASE_USERNAME} --password=${FIREBASE_PASSWORD}